service: cluster

plugins:
  - serverless-offline
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: app.app
  customStage: ${opt:stage, self:provider.stage}
  customEnvironment:
    HASURA_GRAPHQL_ENDPOINT:
      prod: https://anywhr-cluster.herokuapp.com/v1/graphql
    HASURA_ADMIN_SECRET:
      prod: 'random'

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'prod'}

  environment:
    HASURA_GRAPHQL_ENDPOINT: ${self:custom.customEnvironment.HASURA_GRAPHQL_ENDPOINT.${self:custom.customStage}}
    HASURA_ADMIN_SECRET: ${self:custom.customEnvironment.HASURA_ADMIN_SECRET.${self:custom.customStage}}


functions:
  app:
    handler: wsgi_handler.handler
    timeout: 600
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
